version: '3'

services:

  base_focal:
    build:
        context: ./
        dockerfile: Dockerfile._base
        args:
                - base_image=ubuntu:20.04
                - base_dir=/docker
    image: base_focal

  bitcoin.base_focal:
    depends_on:
        - base_focal
    build:
        context: ./
        dockerfile: bitcoin/Dockerfile._base
        args:
                - base_image=base_focal
    image: bitcoin/base_focal

  bitcoin.ubuntu:
    depends_on:
        - bitcoin.base_focal
    build:
        context: ./
        dockerfile: bitcoin/Dockerfile.ubuntu
    image: bitcoin/ubuntu
    container_name: bitcoin.ubuntu
    volumes:
        - ${PROJECTS_DIR:-..}/bitcoin:/projects/bitcoin
    ports:
        - "8332-8333:8332-8333"
        - "18332-18333:18332-18333"